module.exports = {
  eventType: 'auto',
  width: 6,
  height: '90vh',
  dotSize: 24,
  dotHeight: null,
  dotWidth: null,
  min: 2,
  max: 20,
  interval: 1,
  disabled: false,
  show: true,
  realTime: false,
  tooltip: 'always',
  clickable: true,
  tooltipDir: 'right',
  piecewise: false,
  lazy: false,
  reverse: true,
  speed: 0.5,
  formatter: null,
  bgStyle: null,
  sliderStyle: null,
  tooltipStyle: null,
  processStyle: null,
  piecewiseStyle: null,
  direction: 'vertical',
  class: 'slider vertical'
}
